credentials:
  users:
    sampleuser:
      password: '123456'
      privileges:
        - permissions: [ read, write ]
          spaces: [ bands ]

groups:
  group001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            iproto:
              listen:
                - uri: 'tarantool:3301'  

