version: '3.8'

services:
  tarantool:
    image: tarantool/tarantool:latest
    volumes:
      - ./tarantool.cfg:/etc/tarantool.cfg  # Конфигурация Tarantool
      - ./config.yaml:/etc/tarantool/config.yaml  # Монтируем config.yaml
    environment:
      - TARANTOOL_CFG=/etc/tarantool/config.yaml  # Указываем путь к config.yaml
    command: tarantool --config /etc/tarantool/config.yaml
      - TARANTOOL_REPLICATION=true
      - TARANTOOL_INSTANCE_NAME=instance-001
      - TARANTOOL_REPLICASET_NAME=replicaset-001
    ports:
      - "3302:3301"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - tarantool
    environment:
      TARANTOOL_HOST: tarantool
      TARANTOOL_PORT: 3301
      TARANTOOL_USER: sampleuser
      TARANTOOL_PASSWORD: 123456
    restart: always

