version: '3.8'

services:
  tarantool:
    image: tarantool/tarantool:latest
    volumes:
      - ./tarantool.cfg:/etc/tarantool.cfg  # Конфигурация Tarantool
      - ./config.yaml:/etc/tarantool/config.yaml  # Монтируем config.yaml
      - ./init.lua:/etc/tarantool/init.lua
    environment:
      TARANTOOL_REPLICATION: "true"
      TARANTOOL_INSTANCE_NAME: "instance-001"
      TARANTOOL_REPLICASET_NAME: "replicaset-001"
    command: tarantool --config /etc/tarantool/config.yaml
    command: tarantool /etc/tarantool/init.lua
    ports:
      - "3302:3301"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - tarantool
    environment:
      TARANTOOL_HOST: tarantool
      TARANTOOL_PORT: 3301
      TARANTOOL_USER: sampleuser
      TARANTOOL_PASS: 123456
    restart: always

